[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.poetry.dependencies]
requests = "2.28.2"
google-auth-oauthlib = "1.2.2"
todoist-api-python = "3.1.0"
PyMySQL = "1.0.2"
loguru = "0.6.0"